build(deps): update dependency prettier to v3.9.5 (#450)
This PR contains the following updates:

| Package | Change |
[Age](https://docs.renovatebot.com/merge-confidence/) |
[Confidence](https://docs.renovatebot.com/merge-confidence/) |
|---|---|---|---|
| [prettier](https://prettier.io)
([source](https://redirect.github.com/prettier/prettier)) | [`3.8.4` →
`3.9.5`](https://renovatebot.com/diffs/npm/prettier/3.8.4/3.9.5) |
![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.9.5?slim=true)
|
![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.8.4/3.9.5?slim=true)
|

---

### Release Notes

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.9.5`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#395)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.9.4...3.9.5)


[diff](https://redirect.github.com/prettier/prettier/compare/3.9.4...3.9.5)

##### Markdown: Cap ordered list mark at 999,999,999
([#&#8203;19351](https://redirect.github.com/prettier/prettier/pull/19351)
by [@&#8203;tats-u](https://redirect.github.com/tats-u))

CommonMark parsers only support ordered list item numbers up to
999,999,999.

With this change, Prettier now caps the ordered list item number at
999,999,999 to ensure that the output is correctly parsed as an ordered
list by CommonMark parsers. Numbers larger than 999,999,999 are not
parsed as list item numbers and are left unchanged in the output:

<!-- prettier-ignore -->

```markdown
<!-- Input -->
999999998. text
999999998. text
999999998. text
999999998. text

1234567890123456789012) text

<!-- Prettier 3.9.4 -->
999999998. text
999999999. text
1000000000. text
1000000001. text

1234567890123456789012) text

<!-- Prettier 3.9.5 -->
999999998. text
999999999. text
999999999. text
999999999. text

1234567890123456789012) text
```

##### Markdown: Avoid corrupting empty link with title
([#&#8203;19487](https://redirect.github.com/prettier/prettier/pull/19487)
by [@&#8203;andersk](https://redirect.github.com/andersk))

Do not remove `<>` from an inline link or image with an empty URL and a
title, as this removal would change its interpretation.

<!-- prettier-ignore -->

```md
<!-- Input -->
[link](<> "title")

<!-- Prettier 3.9.4 -->
[link]( "title")

<!-- Prettier 3.9.5 -->
[link](<> "title")
```

##### Less: Remove extra spaces after `[` in map lookups
([#&#8203;19503](https://redirect.github.com/prettier/prettier/pull/19503)
by [@&#8203;kovsu](https://redirect.github.com/kovsu))

<!-- prettier-ignore -->

```less
// Input
.foo {
  color: #theme[ primary];
  color: #theme[@&#8203;name];
  color: #theme[@&#8203;@&#8203;name];
}

// Prettier 3.9.4
.foo {
  color: #theme[ primary];
  color: #theme[ @&#8203;name];
  color: #theme[ @&#8203;@&#8203;name];
}

// Prettier 3.9.5
.foo {
  color: #theme[primary];
  color: #theme[@&#8203;name];
  color: #theme[@&#8203;@&#8203;name];
}
```

##### CSS: Prevent addition space in `type()` with `+`
([#&#8203;19516](https://redirect.github.com/prettier/prettier/pull/19516)
by [@&#8203;bigandy](https://redirect.github.com/bigandy))

This fixes the addition space before `+` in CSS `type()` declaration.
For example `type(<number>+)` was being converted into `type(<number>
+)` which is invalid CSS and does not work.

<!-- prettier-ignore -->

```css
/* Input */
div {
  border-radius: attr(br type(<length>+));
}

/* Prettier 3.9.4 */
div {
  border-radius: attr(br type(<length> +));
}

/* Prettier 3.9.5 */
div {
  border-radius: attr(br type(<length>+));
}
```

##### Less: Remove spaces between merge markers and colons
([#&#8203;19517](https://redirect.github.com/prettier/prettier/pull/19517)
by [@&#8203;kovsu](https://redirect.github.com/kovsu))

<!-- prettier-ignore -->

```less
// Input
a {
  box-shadow  +  : 0 0 1px #&#8203;000;
}

// Prettier 3.9.4
a {
  box-shadow+  : 0 0 1px #&#8203;000;
}

// Prettier 3.9.5
a {
  box-shadow+: 0 0 1px #&#8203;000;
}
```

##### Markdown: Preserve wiki links with aliases
([#&#8203;19527](https://redirect.github.com/prettier/prettier/pull/19527)
by [@&#8203;kovsu](https://redirect.github.com/kovsu))

<!-- prettier-ignore -->

```markdown
<!-- Input -->
[[Foo:Bar]]

<!-- Prettier 3.9.4 -->
[[Foo]]

<!-- Prettier 3.9.5 -->
[[Foo:Bar]]
```

##### TypeScript: Fix comments being dropped on shorthand `type`
import/export specifiers
([#&#8203;19565](https://redirect.github.com/prettier/prettier/pull/19565)
by [@&#8203;kirkwaiblinger](https://redirect.github.com/kirkwaiblinger))

<!-- prettier-ignore -->

```tsx
// Input
export { type /* comment */ T } from "foo";
import { type /* comment */ T } from "foo";

// Prettier 3.9.4
Error: Comment "comment" was not printed. Please report this error!

// Prettier 3.9.5
export { type /* comment */ T } from "foo";
import { type /* comment */ T } from "foo";
```

##### Miscellaneous: Preserving comments' `placement` property
([#&#8203;19567](https://redirect.github.com/prettier/prettier/pull/19567)
by [@&#8203;Janther](https://redirect.github.com/Janther))

Prettier\@&#8203;3.9.0 deleted an undocumented property on comments,
which was already used by plugins, `comment.placement` is now available
again after comment attach.

##### Flow: Stop enforcing empty module declaration to break
([#&#8203;19568](https://redirect.github.com/prettier/prettier/pull/19568)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```flow
// Input
declare module "foo" {}

// Prettier 3.9.4
declare module "foo" {
}

// Prettier 3.9.5
declare module "foo" {}
```

##### Angular: Support expression for exhaustive typechecking
([#&#8203;19571](https://redirect.github.com/prettier/prettier/pull/19571)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```html
<!-- Input -->
@&#8203;switch (state.mode) {
  @&#8203;default never(state);
}

<!-- Prettier 3.9.4 -->
@&#8203;switch (state.mode) {
  @&#8203;default never;
}

<!-- Prettier 3.9.5 -->
@&#8203;switch (state.mode) {
  @&#8203;default never(state);
}
```

##### TypeScript: Ignore comments inside mapped type when checking type
parameter comments
([#&#8203;19572](https://redirect.github.com/prettier/prettier/pull/19572)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```tsx
// Input
foo<{
  // comment
  [key in keyof Foo]: number
}>();

// Prettier 3.9.4
foo<
  {
    // comment
    [key in keyof Foo]: number;
  }
>();

// Prettier 3.9.5
foo<{
  // comment
  [key in keyof Foo]: number;
}>();
```

##### Less: Fix adjacent block comments being corrupted
([#&#8203;19574](https://redirect.github.com/prettier/prettier/pull/19574)
by [@&#8203;kovsu](https://redirect.github.com/kovsu))

<!-- prettier-ignore -->

```less
// Input
/* a *//* b */
/* a */* {
  color: red;
}

// Prettier 3.9.4
/* a */
/* b */
/* a * {
  color: red;
}

// Prettier 3.9.5
/* a */ /* b */
/* a */
* {
  color: red;
}
```

##### JavaScript: Handle dangling comments in `SwitchStatement`
([#&#8203;19581](https://redirect.github.com/prettier/prettier/pull/19581)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
switch (foo) {
 // comment
}

// Prettier 3.9.4
switch (
  foo
  // comment
) {
}

// Prettier 3.9.5
switch (foo) {
  // comment
}
```

##### TypeScript: Remove space in comment-only object type
([#&#8203;19583](https://redirect.github.com/prettier/prettier/pull/19583)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```tsx
// Input
var foo = {
  /* comment */
};
type Foo = {
  /* comment */
};

// Prettier 3.9.4
var foo = {/* comment */};
type Foo = { /* comment */ };

// Prettier 3.9.5
var foo = {/* comment */};
type Foo = {/* comment */};
```

###
[`v3.9.4`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#394)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.9.3...3.9.4)


[diff](https://redirect.github.com/prettier/prettier/compare/3.9.3...3.9.4)

##### Angular: Format `@content(name)` -> `@content (name)` to align
with other block syntax
([#&#8203;19499](https://redirect.github.com/prettier/prettier/pull/19499)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```html
<!-- Input -->
<FancyButton [label]="title">
  @&#8203;content (icon) {
    <span>Icon!</span>
  }
  @&#8203;content (description) {
    <span>Description text</span>
  }
  <span>Other children</span>
</FancyButton>

<!-- Prettier 3.9.3 -->
<FancyButton [label]="title">
  @&#8203;content(icon) {
    <span>Icon!</span>
  }
  @&#8203;content(description) {
    <span>Description text</span>
  }
  <span>Other children</span>
</FancyButton>

<!-- Prettier 3.9.4 -->
<FancyButton [label]="title">
  @&#8203;content (icon) {
    <span>Icon!</span>
  }
  @&#8203;content (description) {
    <span>Description text</span>
  }
  <span>Other children</span>
</FancyButton>
```

###
[`v3.9.3`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#393)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.9.2...3.9.3)


[diff](https://redirect.github.com/prettier/prettier/compare/3.9.1...3.9.3)

##### Markdown: Fix unexpected removal of characters in liquid syntax
([#&#8203;19489](https://redirect.github.com/prettier/prettier/pull/19489)
by [@&#8203;seiyab](https://redirect.github.com/seiyab))

<!-- prettier-ignore -->

```md
// Input
<!-- Input -->
{{ page.title
}} text

<!-- Prettier 3.9.1 -->
{{ page.title
 text

<!-- Prettier 3.9.3 -->
{{ page.title
}} text
```

##### TypeScript: Allow decorators to be used with declare on class
fields
([#&#8203;19492](https://redirect.github.com/prettier/prettier/pull/19492)
by [@&#8203;evoactivity](https://redirect.github.com/evoactivity))

Extensively used within the Ember ecosystem, decorators with `declare`
on class fields will ignore the babel parser error and allow Prettier to
format the code without breaking it.

<!-- prettier-ignore -->

```ts
// Input
export default class ProjectStatusComponent extends Component<ProjectStatusSig> {
  @&#8203;service declare server: ServerService;
}

// Prettier 3.9.1
// SyntaxError: Decorators can't be used with a declare field. (2:3)
//  1 | export default class ProjectStatusComponent extends Component<ProjectStatusSig> {
//> 2 |   @&#8203;service declare server: ServerService;
//    |   ^
//  3 | }

// Prettier 3.9.3
export default class ProjectStatusComponent extends Component<ProjectStatusSig> {
  @&#8203;service declare server: ServerService;
}
```

###
[`v3.9.2`](https://redirect.github.com/prettier/prettier/compare/3.9.1...3.9.2)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.9.1...3.9.2)

###
[`v3.9.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#391)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.9.0...3.9.1)


[diff](https://redirect.github.com/prettier/prettier/compare/3.9.0...3.9.1)

##### CLI: Fix ignored file has been cached incorrectly
([#&#8203;19483](https://redirect.github.com/prettier/prettier/pull/19483)
by [@&#8203;kovsu](https://redirect.github.com/kovsu))

Bug details
[#&#8203;18016](https://redirect.github.com/prettier/prettier/issues/18016)

###
[`v3.9.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#390)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.8.5...3.9.0)


[diff](https://redirect.github.com/prettier/prettier/compare/3.8.5...3.9.0)

🔗 [Release Notes](https://prettier.io/blog/2026/06/27/3.9.0)

###
[`v3.8.5`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#385)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.8.4...3.8.5)


[diff](https://redirect.github.com/prettier/prettier/compare/3.8.4...3.8.5)

##### Flow: Support `readonly` as a variance annotation
([#&#8203;19022](https://redirect.github.com/prettier/prettier/pull/19022)
by [@&#8203;marcoww6](https://redirect.github.com/marcoww6))

Flow now accepts `readonly` as a property variance annotation,
equivalent to `+` (covariant/read-only).

<!-- prettier-ignore -->

```jsx
// Input
type T = {
  readonly foo: string,
};

// Prettier 3.8.4
SyntaxError

// Prettier 3.8.5
type T = {
  readonly foo: string,
};
```

</details>

---

### Configuration

📅 **Schedule**: (in timezone America/Los_Angeles)

- Branch creation
  - At any time (no schedule defined)
- Automerge
  - At any time (no schedule defined)

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0My4yNTkuMiIsInVwZGF0ZWRJblZlciI6IjQzLjI1OS4yIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJkZXBlbmRlbmNpZXMiXX0=-->

Co-authored-by: jonahsnider[bot] <287348350+jonahsnider[bot]@users.noreply.github.com>